---
version: 2

workflows:
  version: 2
  main:
    jobs:
    - test_86x
    - test_87x
  sync:
    jobs:
    - sync_drupalorg:
        filters:
          tags:
            only: /.*/
          branches:
            only: /[7-9].x-.*/

jobs:
  sync_drupalorg:
    docker:
    - image: previousnext/pnx-packager
    working_directory: /data
    environment:
      GIT_MIRROR_URL: git@git.drupal.org:project/dashboard_connector.git
    steps:
    - checkout
    - add_ssh_keys
    - run: ssh-keyscan git.drupal.org >> /root/.ssh/known_hosts
    - run:
        name: Add drupal.org git remote
        command: git remote add drupal "${GIT_MIRROR_URL}"
    - run:
        name: Push to drupal.org git remote
        command: git push drupal "${CIRCLE_BRANCH:-refs/tags/${CIRCLE_TAG}}"

  test: &test
    docker:
      - image: previousnext/php-apache:7.2-3.x-dev
        environment:
          MODULE_NAME: dashboard_connector
          SIMPLETEST_BASE_URL: http://127.0.0.1
          SIMPLETEST_DB: mysql://drupal:drupal@127.0.0.1/local
      - image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: local
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
    working_directory: /data/app
    steps:
    - add_ssh_keys
    - run:
        name: Download specified drupal version
        command: |
          git clone --depth 1 --branch ${DRUPAL_BRANCH} \
            https://git.drupal.org/project/drupal.git .
    - run:
        name: Fetch drupal dependencies
        command: |
          composer install --prefer-dist --no-progress
          composer require --dev --prefer-dist --no-progress --update-with-dependencies \
            drush/drush:~9.4 \
            phpunit/phpunit:~6.5 \

    - checkout:
        path: modules/${MODULE_NAME}
    - run:
        name: Lint PHP against Drupal coding standards
        command: |
          vendor/bin/phpcs \
            --standard=vendor/drupal/coder/coder_sniffer/Drupal \
            --extensions=php,module,inc,install,test,profile,theme,css,info \
            --ignore=*.md \
            modules/${MODULE_NAME}
    - run:
        name: Install drupal
        command: |
          mkdir -p sites/default/files/tmp sites/default/private /data/app/sites/simpletest/browser_output ../build/logs/phpunit
          chmod -R 2775 sites/default/files sites/default/private sites/simpletest ../build/logs
          vendor/bin/drush -yv site-install minimal --db-url="${SIMPLETEST_DB}"
          vendor/bin/drush -yv en ${MODULE_NAME} simpletest
          chown -R apache:apache /data

    - run: httpd -k restart
    - run:
        name: Run unit tests
        command: |
          su -m apache -s /bin/bash -c "./vendor/bin/phpunit -c core/phpunit.xml.dist --log-junit build/logs/phpunit/phpunit.xml modules/${MODULE_NAME}"
    - store_test_results:
        path: build/logs

  test_86x:
    <<: *test
    environment:
    - DRUPAL_BRANCH: 8.6.x
  test_87x:
    <<: *test
    environment:
    - DRUPAL_BRANCH: 8.7.x
